baseURL = "https://calaglinpilot.github.io/notre-nid-en-chantier/"
languageCode = 'fr-FR'
title = 'Notre nid en chantier'

[pagination]
	pagerSize = 10

[params]
	description = "De l'achat à l'emménagement en passant par les travaux : suivez nous dans notre nouvelle belle aventure"
	author = "Visabelle"
	# Apparence
	defaultTheme = "auto" # auto, dark, light
	ShowBreadCrumbs = true
	ShowReadingTime = true
	ShowShareButtons = false
	ShowPostNavLinks = true
	mainSections = []
	ShowCodeCopyButtons = true
	enableEmoji = true

# Menu principal
[[menu.main]]
	identifier = "billets"
  	name = "Billets"
  	url = "/billets/"
  	weight = 20

[[menu.main]]
	identifier = "categories"
	name = "Catégories"
	url = "/categories/"
	weight = 30

[[menu.main]]
	identifier = "rss"
	name = "Flux RSS"
	url = "/index.xml"
	weight = 35

[outputs]
	home = ["HTML", "RSS", "JSON"]

[[module.imports]]
	path = "github.com/adityatelange/hugo-PaperMod"

[caches]
	[caches.images]
		dir = ":cacheDir/images"
