baseURL = "https://calaglinpilot.github.io/notre-nid-en-chantier/"
languageCode = 'fr-FR'
title = 'Notre nid en chantier'

[pagination]
	pagerSize = 10

[params]
	description = "De l'achat à l'emménagement en passant par les travaux : suivez nous dans notre nouvelle belle aventure"
	author = "Visabelle"
	# Apparence
	defaultTheme = "auto" # auto, dark, light
	ShowBreadCrumbs = true
	ShowReadingTime = true
	ShowShareButtons = true
	ShowPostNavLinks = true
	ShowCodeCopyButtons = true

# Menu principal
[[menu.main]]
	identifier = "posts"
  	name = "Articles"
  	url = "/posts/"
  	weight = 20

[outputs]
	home = ["HTML", "RSS", "JSON"]

[[module.imports]]
	path = "github.com/adityatelange/hugo-PaperMod"

[caches]
	[caches.images]
		dir = ":cacheDir/images"


